### ISSUE TITLE
0x0B

### ISSUE THREAD

**Issue by 9ak47er** [haozi/xss-demo#6]
![image](https://user-images.githubusercontent.com/16465253/43258642-155ebd8e-9106-11e8-906e-ea1a8a4951d7.png)
大写也能执行

**Comment by spacesec** [comment]
本地服务器放了一个1.js(js的内容是alert(1))但是好像弹不出来

**Comment by haozi** [comment]
本地是 http 环境吧，xss.haozi.me 是 https 的
